services:
  px4-sitl:
    image: px4-gazebo-sitl:latest
    container_name: px4-sitl
    network_mode: host
    command: >
      bash -c "
      make px4_sitl gz_x500_mono_cam &
      sleep 500
      "

    healthcheck:
      test: ["CMD-SHELL", "ss -uln | grep -q 14540"]
      interval: 1m
      timeout: 10s
      start_period: 5m
      retries: 30

  ros2:
    image: ros2:latest
    container_name: ros2-node
    network_mode: host  # Must match px4-sitl's network
    depends_on:
      px4-sitl:
        condition: service_healthy
    command: >
      bash -c "
      sleep infinity
      "