version: '3.8'

services:
  px4-sitl:
    image: px4-gazebo-sitl:latest
    container_name: px4-sitl
    network_mode: host  # Required for MAVLink/ROS 2 communication
    command: >
      bash -c "
      cd /PX4-Autopilot &&
      make px4_sitl gz_x500_mono_cam &&
      sleep infinity
      "
    healthcheck:
      test: ["CMD", "netstat", "-anp", "|", "grep", "14540"]
      interval: 1s
      timeout: 30s
      retries: 30

  ros2:
    image: ros2:latest
    container_name: ros2-node
    network_mode: host  # Must match px4-sitl's network
    depends_on:
      px4-sitl:
        condition: service_healthy
    command: >
      bash -c "
      sleep 5 &&  # Wait for PX4 to initialize
      ros2 run mavros mavros_node __ns:=/uav1 _fcu_url:='udp://:14540@127.0.0.1:14540'
      "